services:
#    numo.example:
#        class: NumoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.registration:
        class: NumoBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: NumoBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
