
# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: email
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "NumoRegistration", "NumoProfile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "NumoRegistration", "NumoProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "NumoRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "NumoRegistration", "NumoProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "NumoRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "NumoRegistration", "NumoProfile", "ResetPassword", "ChangePassword"]

NumoBundle\Entity\User:
    properties:
        name:
            - NotBlank:
                message: fos_user.field.blank
                groups: [ "NumoRegistration", "NumoProfile" ]
            - Length:
                min: 1
                max: 100
                minMessage: "Le nom est trop court"
                maxMessage: "Le nom est trop long"
                groups: [ "NumoRegistration", "NumoProfile" ]
        firstname:
            - NotBlank:
                message: fos_user.field.blank
                groups: [ "NumoRegistration", "NumoProfile" ]
            - Length:
                min: 1
                max: 100
                minMessage: "Le prénom est trop court"
                maxMessage: "Le prénom est trop long"
                groups: [ "UserRegistration", "NumoProfile" ]
        description:
            - Length:
                max: 653
                maxMessage: "Le message est trop long"
                groups: [ "UserRegistration", "NumoProfile" ]
        imageUrl:
            - Image:
                maxSize: "1024k"
                maxSizeMessage: "L'image est trop lourde"
                mimeTypes: ["image/png", "image/jpg", "image/jpeg", "image/gif"]
                mimeTypesMessage: "L'image n'a pas un format valide"
                groups: [ "UserRegistration", "NumoProfile" ]
        trust:
            - NotBlank:
                message: fos_user.field.blank
                groups: [ "NumoRegistration", "NumoProfile" ]
        webSite:
            - Length:
                min: 3
                max: 255
                minMessage: "Le lien est trop court"
                maxMessage: "Le lien est trop long"
                groups: [ "UserRegistration", "NumoProfile" ]
        freeText:
            - Length:
                min: 3
                max: 5550
                minMessage: "Le texte est trop court"
                maxMessage: "Le texte est trop long"
                groups: [ "UserRegistration", "NumoProfile" ]
        phone:
            - Length:
                min: 3
                max: 5550
                minMessage: "Le numéro est trop court"
                maxMessage: "Le numéro est trop long"
                groups: [ "UserRegistration", "NumoProfile" ]
        address:
            - Length:
                max: 250
                maxMessage: "L'adresse saisie est trop longue"
                groups: [ "UserRegistration", "NumoProfile" ]
        postalCode:
            - Length:
                min: 5
                max: 7
                minMessage: "Le code postal est trop court"
                maxMessage: "Le code postal est trop long"
                groups: [ "UserRegistration", "NumoProfile" ]
        city:
            - Length:
                min: 3
                max: 250
                minMessage: "Le texte saisi est trop court"
                maxMessage: "Le texte saisi est trop long"
                groups: [ "UserRegistration", "NumoProfile" ]
        facebook:
            - Length:
                min: 3
                minMessage: "Le texte saisi est trop court"
                groups: [ "UserRegistration", "NumoProfile" ]
        twitter:
            - Length:
                min: 3
                minMessage: "Le texte saisi est trop court"
                groups: [ "UserRegistration", "NumoProfile" ]
        linkedin:
            - Length:
                min: 3
                minMessage: "Le texte saisi est trop court"
                groups: [ "UserRegistration", "NumoProfile" ]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "NumoRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "NumoRegistration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "NumoRegistration", "NumoProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "NumoRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "NumoRegistration", "NumoProfile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "NumoRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "NumoRegistration", "NumoProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "NumoRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "NumoRegistration" ]